### ISSUE TITLE
缺少yaha模块

### ISSUE THREAD

**Issue by whucszhou1234** [crownpku/Rasa_NLU_Chi#28]
在初次运行时，缺少yaha模块。具体异常信息如下：
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zhoumeng/rasa_nlu/Rasa_NLU_Chi-master/rasa_nlu/train.py", line 125, in <module>
    do_train(config)
  File "/home/zhoumeng/rasa_nlu/Rasa_NLU_Chi-master/rasa_nlu/train.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "rasa_nlu/model.py", line 126, in __init__
    components.validate_requirements(config.pipeline)
  File "rasa_nlu/components.py", line 77, in validate_requirements
    from rasa_nlu import registry
  File "rasa_nlu/registry.py", line 39, in <module>
    from rasa_nlu.tokenizers.yaha_tokenizer import YahaTokenizer
  File "rasa_nlu/tokenizers/yaha_tokenizer.py", line 25, in <module>
    from yaha import Cuttor
ImportError: No module named yaha

**Comment by crownpku** [comment]
请先安装yaha模块：
`pip install yaha`

**Comment by nacyzhaomin** [comment]
yaha 支持python3吗？这不是用jieba分词么？怎么用yaha 了呢？

**Comment by crownpku** [comment]
之前的反馈是yaha不支持python3. 分词模块可以在config中配置成为jieba，yaha只是提供另一个分词选择。

**Comment by nacyzhaomin** [comment]
不好意思，我还想再问一下，您在某一个回答中说，用jieba分词版本是哪一个，我的问题一直报要装yaha。但是程序只用结巴分词呀。没懂。。急求教

**Comment by nacyzhaomin** [comment]
config配置为jieba是在哪里配置，是在nlu这里还是在调用nlu的项目里配置

**Comment by crownpku** [comment]
新commit已经取消了对yaha的支持。
