### ISSUE TITLE
怎么联系大神 有没有交流群

### ISSUE THREAD

**Issue by yoke233** [crownpku/rasa_nlu_chi#3]
怎么联系大神 有没有交流群
对这个系统很感兴趣. 但是本人是新接触NLU相关

**Comment by crownpku** [comment]
你可以去rasa.ai上面，有很多资料。有具体中文应用相关问题的话可以再发issue来讨论，谢谢~

**Comment by yoke233** [comment]
trained MITIE word vector
这个训练过的文件能否共享一份

rasa_nlu_chi 和 rasa_nlu 以哪个为准?

**Comment by crownpku** [comment]
word vector因为牵扯到一些语料版权问题，抱歉暂时不能共享。
你可以自己找一些中文语料用MITIE进行训练。

rasa_nlu_chi是稳定版，rasa_nlu是非稳定的开发版。

**Comment by yoke233** [comment]
能否指导下怎么生成total_word_feature_extractor.dat文件.

**Comment by crownpku** [comment]
更新了Readme，你可以看下~

**Comment by crownpku** [comment]
[中文blog](http://www.crownpku.com//2017/07/27/%E7%94%A8Rasa_NLU%E6%9E%84%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84%E4%B8%AD%E6%96%87NLU%E7%B3%BB%E7%BB%9F.html)

详细介绍了如何生成total_word_feature_extractor.dat文件，也分享了一个我自己训练的结果在百度网盘。

**Comment by yoke233** [comment]
感谢分享训练的结果. 之前生成的时候没有大内存机器 就自己笔记本16g 跑了2下挂掉了.
然后换了spacy, 但是没有中文支持, 自己做了套发现识别不是很准确, 也可能是步骤不太对

**Comment by fzy0728** [comment]
我的训练数据多起来后会出现这样的编码问题，大神遇见过吗？
```
Building prefix dict from the default dictionary ...                                                  
Loading model from cache /tmp/jieba.cache                                                             
Dumping model to file cache /tmp/jieba.cache                                                          
Dump cache file failed.                                                                               
Traceback (most recent call last):                                                                    
  File "/home/fuziyu/.local/lib/python2.7/site-packages/jieba/__init__.py", line 152, in initialize   
    _replace_file(fpath, cache_file)                                                                  
OSError: [Errno 1] Operation not permitted                                                            
Loading model cost 1.372 seconds.                                                                     
Prefix dict has been built succesfully.                                                               
Traceback (most recent call last):                                                                    
  File "text.py", line 43, in <module>                                                                
    print interpreter.parse(u"我想看刘德华电影")                                                      
  File "/home/fuziyu/rasa_nlu/rasa_nlu_chi/rasa_nlu/model.py", line 295, in parse                     
    component.process(message, **self.context)                                                        
  File "/home/fuziyu/rasa_nlu/rasa_nlu_chi/rasa_nlu/extractors/mitie_entity_extractor.py", line 118, i
n process                                                                                             
    ents = self.extract_entities(message.text, message.get("tokens"), mitie_feature_extractor)        
  File "/home/fuziyu/rasa_nlu/rasa_nlu_chi/rasa_nlu/extractors/mitie_entity_extractor.py", line 48, in
 extract_entities                                                                                     
    entities = self.ner.extract_entities(tokens_strs, feature_extractor)                              
  File "/home/fuziyu/.local/lib/python2.7/site-packages/mitie/mitie.py", line 278, in extract_entities
    tags = self.get_possible_ner_tags()                                                               
  File "/home/fuziyu/.local/lib/python2.7/site-packages/mitie/mitie.py", line 258, in get_possible_ner
_tags                                                                                                 
    return [to_default_str_type(_f.mitie_get_named_entity_tagstr(self.__obj, i)) for i in xrange(num)]
  File "/home/fuziyu/.local/lib/python2.7/site-packages/mitie/mitie.py", line 129, in to_default_str_t
ype                                                                                                   
    string = string.encode('utf-8')                                                                   
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)     

```
