### ISSUE TITLE
python3.6运行出现OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by githubwbs** [crownpku/Rasa_NLU_Chi#31]
**Rasa NLU version** (e.g. `0.7.3`): 0.10.6

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):mitie-jieba-sklearn

**Operating system** (windows, osx, ...):windows7,X64,python3.6

**Issue**:
您好！我按照教程使用python3.6训练模型，到了
python -m rasa_nlu.train -c sample_configs/config_jieba_mitie_sklearn.json
这一步时出现了以下错，不知怎么解决：

D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master>python -m rasa_nlu
.train -c sample_configs/config_jieba_mitie_sklearn.json
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\YJY\AppData\Local\Temp\jieba.cache
DEBUG:jieba:Loading model from cache C:\Users\YJY\AppData\Local\Temp\jieba.cache

Loading model cost 0.477 seconds.
DEBUG:jieba:Loading model cost 0.477 seconds.
Prefix dict has been built succesfully.
DEBUG:jieba:Prefix dict has been built succesfully.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master\rasa_nlu\t
rain.py", line 125, in <module>
    do_train(config)
  File "D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master\rasa_nlu\t
rain.py", line 111, in do_train
    trainer = Trainer(config, component_builder)
  File "D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master\rasa_nlu\m
odel.py", line 126, in __init__
    components.validate_requirements(config.pipeline)
  File "D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master\rasa_nlu\c
omponents.py", line 83, in validate_requirements
    failed_imports.update(find_unavailable_packages(component_class.required_pac
kages()))
  File "D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master\rasa_nlu\c
omponents.py", line 68, in find_unavailable_packages
    importlib.import_module(package)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import
_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\聊天机器人项目\机器人框架\RASA主体框架\Rasa_NLU_Chi-master\mitie.py",
 line 36, in <module>
    _f = ctypes.CDLL(most_recent)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Content of configuration file** (if used & relevant):
```json

```

**Comment by nacyzhaomin** [comment]
楼上的问题解决了吗？我的问题是要装yaha？不是用jieba吗？没懂

**Comment by crownpku** [comment]
@nacyzhaomin 已经取消了对yaha的支持
