### ISSUE TITLE
我win7，python3.5,安装mitle一直不成功，谁有step by step的方法？

### ISSUE THREAD

**Issue by kevinsay** [crownpku/Rasa_NLU_Chi#39]
**Rasa NLU version** (e.g. `0.7.3`):

**Used backend / pipeline** (`mitie`, `spacy_sklearn`, ...):

**Operating system** (windows, osx, ...):

**Issue**:

**Content of configuration file** (if used & relevant):
```json

```

**Comment by HwarLee** [comment]
pip install git+https://github.com/mit-nlp/MITIE.git

**Comment by BobCN2017** [comment]
git clone https://github.com/mit-nlp/MITIE.git
然后进入clone后目录，执行：
python setup.py install

**Comment by zymprogramer** [comment]
我是win7 python3,6， 我下载了mitie的github项目，然后直接在源码地址内运行python setup.py install. 值得注意的是得下载CMake，并加入到path

**Comment by zizhec** [comment]
我也是 win7, 64位， py3.5. 搞死都搞不出来。

PS D:\python\project\MITIE> python.exe .\setup.py install
running install
running build
CMake Error: Error: generator platform: x64
Does not match the platform used previously:
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
Traceback (most recent call last):
  File ".\setup.py", line 67, in <module>
    'License :: Boost License',
  File "D:\python\py35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\python\py35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\python\py35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\python\py35\lib\distutils\command\install.py", line 539, in run
    self.run_command('build')
  File "D:\python\py35\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\python\py35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File ".\setup.py", line 23, in run
    subprocess.check_call(['cmake', '..', '-A', 'x64'])
  File "D:\python\py35\lib\subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '..', '-A', 'x64']' returned non-zero exit status 1

> 我是win7 python3,6， 我下载了mitie的github项目，然后直接在源码地址内运行python setup.py install. 值得注意的是得下载CMake，并加入到path
