### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by loveJasmine** [crownpku/Rasa_NLU_Chi#66]
mldl@ub1604:~/ub16_prj/rasa_nlu_chi$ python -m rasa_nlu.train -c sample_configs/config_jieba_mitie_sklearn.json -d data/examples/rasa/demo-rasa_zh_medical.json 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mldl/ub16_prj/rasa_nlu_chi/rasa_nlu/train.py", line 174, in <module>
    num_threads=cmdline_args.num_threads)
  File "/home/mldl/ub16_prj/rasa_nlu_chi/rasa_nlu/train.py", line 143, in do_train
    trainer = Trainer(cfg, component_builder)
  File "rasa_nlu/model.py", line 146, in __init__
    components.validate_requirements(cfg.component_names)
  File "rasa_nlu/config.py", line 146, in component_names
    return [c.get("name") for c in self.pipeline]
AttributeError: 'unicode' object has no attribute 'get'

**Comment by giggslam** [comment]
is it related to python "Unicode" setting?
try to set `export LC_ALL=en_US.UTF-8` in your terminal session before running it.

**Comment by D-32** [comment]
I had the above issue after updating to a new version of rasa. I had to migrate the config (json) to the new yaml format and make sure all strings are in quotes "" to get everything to work again.

**Comment by lapsule** [comment]
try this:

```sh
python -m rasa_nlu.train -c sample_configs/config_jieba_mitie_sklearn.yml -d ./data/examples/rasa/demo-rasa_zh.json
```
