### ISSUE TITLE
Error loading MITIE model file: data/total_word_feature_extractor_zh.dat

### ISSUE THREAD

**Issue by jiongjiongli** [crownpku/Rasa_NLU_Chi#72]
**Rasa NLU version**:
Latest
**Operating system** (windows, osx, ...):
osx
**Content of model configuration file**:
```yml
language: "zh"

pipeline:
- name: "nlp_mitie"
  model: "data/total_word_feature_extractor_zh.dat"
- name: "tokenizer_jieba"
- name: "ner_mitie"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_mitie"
- name: "intent_classifier_sklearn"

```

**Issue**:
total_word_feature_extractor.dat 是从 [用Rasa_NLU构建自己的中文NLU系统](http://www.crownpku.com/2017/07/27/%E7%94%A8Rasa_NLU%E6%9E%84%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84%E4%B8%AD%E6%96%87NLU%E7%B3%BB%E7%BB%9F.html) 提供的网盘下载的。
mitie.total_word_feature_extractor('data/total_word_feature_extractor_zh.dat')报错：

```
Error loading MITIE model file: data/total_word_feature_extractor_zh.dat
Error deserializing object of type short
   while deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::map
Traceback (most recent call last):
  File "/anaconda2/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda2/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/train.py", line 174, in <module>
    num_threads=cmdline_args.num_threads)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/train.py", line 143, in do_train
    trainer = Trainer(cfg, component_builder)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/model.py", line 149, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/model.py", line 160, in _build_pipeline
    component_name, cfg)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/components.py", line 420, in create_component
    cfg)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/registry.py", line 139, in create_component_by_name
    return component_clz.create(config)
  File "/Users/jiongjiong/proj/git/Rasa_NLU_Chi/rasa_nlu/utils/mitie_utils.py", line 65, in create
    extractor = mitie.total_word_feature_extractor(model_file)
  File "/anaconda2/envs/py36/lib/python3.6/site-packages/mitie/mitie.py", line 830, in __init__
    raise Exception("Unable to load total_word_feature_extractor detector from " + to_default_str_type(filename))
Exception: Unable to load total_word_feature_extractor detector from data/total_word_feature_extractor_zh.dat
```

**Comment by crownpku** [comment]
把config文件中total_word_feature_extractor_zh.dat所在的路径换成绝对路径试一试。

**Comment by jiongjiongli** [comment]
> 把config文件中total_word_feature_extractor_zh.dat所在的路径换成绝对路径试一试。

和路径没有关系，文件已经读取了，但是mitie解析报的错。

**Comment by jiongjiongli** [comment]
已经解决了，是因为未知原因文件格式破坏了，重新下载后就好了😢
