### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 3: invalid continuation byte

### ISSUE THREAD

**Issue by CuteLin** [crownpku/Rasa_NLU_Chi#96]
**Rasa NLU version**:
1.6.0
**Operating system** (windows, osx, ...):
windows10
**Issue**:
按照readme启动rasa服务器后台，然后用curl：
 `curl -XPOST localhost:5000/parse -d "{"q":"我发烧了该吃什么药？", "model": "model_20191229-202428"}" `
服务器报错：
`Traceback (most recent call last):
          File "D:\rasa\Rasa_NLU_Chi-master\rasa_nlu\server.py", line 133, in decorated
            return f(*args, **kwargs)
          File "D:\rasa\Rasa_NLU_Chi-master\rasa_nlu\server.py", line 116, in decorated
            return f(*args, **kwargs)
          File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twisted\internet\defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twisted\internet\defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "D:\rasa\Rasa_NLU_Chi-master\rasa_nlu\server.py", line 224, in parse
            request.content.read().decode('utf-8', 'strict'))
          builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 3: invalid continuation byte`
有兄弟可以帮忙看一下吗？谢谢了

**Comment by CUCLCY** [comment]
您好,请问解决了吗

**Comment by CuteLin** [comment]
> 您好,请问解决了吗

没有，我认为可能是版本问题？这个包是0.12版的
